from __future__ import annotations

from datetime import datetime, timedelta, timezone

from .models import Offer, OfferType, Store


def sample_offers(now: datetime | None = None) -> list[Offer]:
    now = now or datetime.now(timezone.utc)
    return [
        Offer(
            external_id="sample-control",
            title="Control Ultimate Edition",
            store=Store.EPIC,
            url="https://store.epicgames.com/",
            current_price_minor=0,
            normal_price_minor=249900,
            currency="INR",
            discount_percent=100,
            offer_type=OfferType.FREE_TO_KEEP,
            start_at=now - timedelta(hours=1),
            end_at=now + timedelta(days=4),
            genres=("Action", "Atmospheric", "Story Rich"),
            developer="Remedy Entertainment",
            publisher="505 Games",
            image_url="https://cdn1.epicgames.com/offer/sample/control.jpg",
            description="Sample data used only for a local dry run.",
            rarity_hint=True,
            metadata={"source": "sample"},
        ),
        Offer(
            external_id="sample-signalis",
            title="SIGNALIS",
            store=Store.STEAM,
            url="https://store.steampowered.com/",
            current_price_minor=27400,
            normal_price_minor=109900,
            currency="INR",
            discount_percent=75,
            offer_type=OfferType.PAID_DISCOUNT,
            end_at=now + timedelta(days=2),
            review_percent=96,
            review_count=22000,
            review_label="Overwhelmingly Positive",
            genres=("Psychological Horror", "Survival Horror", "Story Rich"),
            developer="rose-engine",
            publisher="Humble Games",
            metadata={"source": "sample"},
        ),
        Offer(
            external_id="sample-nfs-heat",
            title="Need for Speed Heat",
            store=Store.STEAM,
            url="https://store.steampowered.com/",
            current_price_minor=17900,
            normal_price_minor=179900,
            currency="INR",
            discount_percent=90,
            offer_type=OfferType.PAID_DISCOUNT,
            end_at=now + timedelta(days=5),
            review_percent=84,
            review_count=110000,
            review_label="Very Positive",
            genres=("Racing", "Open World"),
            developer="Ghost Games",
            publisher="Electronic Arts",
            metadata={"source": "sample"},
        ),
        Offer(
            external_id="sample-titanfall-2",
            title="Titanfall 2",
            store=Store.STEAM,
            url="https://store.steampowered.com/",
            current_price_minor=14900,
            normal_price_minor=149900,
            currency="INR",
            discount_percent=90,
            offer_type=OfferType.PAID_DISCOUNT,
            end_at=now + timedelta(days=5),
            review_percent=95,
            review_count=240000,
            review_label="Overwhelmingly Positive",
            genres=("Action", "FPS", "Story Rich"),
            developer="Respawn Entertainment",
            publisher="Electronic Arts",
            metadata={"source": "sample"},
        ),
        Offer(
            external_id="sample-mass-effect",
            title="Mass Effect Legendary Edition",
            store=Store.STEAM,
            url="https://store.steampowered.com/",
            current_price_minor=29900,
            normal_price_minor=199900,
            currency="INR",
            discount_percent=85,
            offer_type=OfferType.PAID_DISCOUNT,
            end_at=now + timedelta(days=5),
            review_percent=91,
            review_count=76000,
            review_label="Very Positive",
            genres=("RPG", "Story Rich", "Sci-fi"),
            developer="BioWare",
            publisher="Electronic Arts",
            metadata={"source": "sample"},
        ),
        Offer(
            external_id="sample-soundtrack",
            title="SIGNALIS Soundtrack",
            store=Store.STEAM,
            url="https://store.steampowered.com/",
            current_price_minor=9900,
            normal_price_minor=29900,
            currency="INR",
            discount_percent=67,
            offer_type=OfferType.DLC,
            metadata={"source": "sample"},
        ),
    ]
